name: release site files

on:
  push:
    branches:
      - main # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - 'py/**'

jobs:
  deploy:
    runs-on: ${{ matrix.os }} # 使用ubuntu系统镜像运行自动化脚本
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps: # 自动化步骤
      - name: check out code
        uses: actions/checkout@main # 第一步，下载代码仓库
       
      # 安装node
      - name: install node
        # 使用action库 actions/setup-node 安装node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1

        #安装依赖
      - name: npm
        run: npm install

      # 打包
      - name: package-win
        if: startsWith(matrix.os, 'windows')
        run: npm run electron:build-win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: package-mac
        if: startsWith(matrix.os, 'macos')
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

       # step5: cleanup artifacts in dist_electron
      # - name: cleanup artifacts
      #   run: |
      #     npx rimraf "dist_electron/!(*.exe|*.dmg)"
      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist_electron

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist_electron/**

